Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -26,22 +26,23 @@ jobs:
       run: dotnet build --no-restore
     - name: Install ReportGenerator
       run: dotnet tool install --global dotnet-reportgenerator-globaltool
-
-    - name: Give execute permission to the script
-      run: chmod +x ./genreport.sh  # Replace with your script filename
-
-    - name: Run coverage script
-      run: ./genreport.sh
-
-    - name: Extract Line Coverage from index.html        
+    - name: Run tests with coverage
+      run: dotnet test --settings coverlet.runsettings.xml
+    - name: Generate coverage report
+      run: reportgenerator -reports:*/TestResults/*/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Cobertura
+    - name: Get Overall Line Coverage
       run: |
-          coverage_line=$(grep -oP 'Line coverage[^0-9]*\K[0-9]+\.[0-9]+' coveragereport/index.html)
-          
-          coverage_percentage=$(printf "%.0f" "$coverage_line")
+          COBERTURA_FILE="coveragereport/Cobertura.xml"
 
-          echo "Line coverage: $coverage_percentage%"
-
-          if (( coverage_percentage < 80 )); then
-            echo "Code coverage below threshold (80%)!"
-            exit 1
+          if [[ ! -f "$COBERTURA_FILE" ]]; then
+              echo "Error: Cobertura file not found at $COBERTURA_FILE"
+              exit 1
           fi
+
+          OVERALL_COVERAGE=$(xmllint --xpath "string(/coverage/@line-rate)" "$COBERTURA_FILE")
+          echo "Overall Line Coverage: ${OVERALL_COVERAGE}%"
+          if ($OVERALL_COVERAGE < 0.8); then
+              echo "Coverage is below 80%! Failing the build."
+              exit 1
+          fi
+      
